name: Frontend Actions
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event. \nğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!\nğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner.\nğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Run lint in the repository
        run: |
          npm install && npm run lint
      - run: echo "ğŸ This job's status is ${{ job.status }}."
